name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install dependancies    
      run: npm i
    - name: Intsall playwright global
      run: npx playwright install
    - name: Run the client and server
      run: npm run server & npm start & 
    - name: Test the app
      run: npm test
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-d13k6oali9vc738lnimg
          api-key: rnd_ILCQKlQBErumTXm21PRb0AGUnWYy
          wait-for-success: true
